Service:
  RegionId: cn-hangzhou
  DeployType: ros
  OperationMetadata:
    StatusOperationConfigs:
      - TemplateName: '单机版'
        SupportOperations:
          - Start
          - Stop
          - Restart
    SupportBackup: true
  DeployMetadata:
    SupplierDeployMetadata:
      FileArtifactRelation:
        '{{ computenest::file::aliyun-computenest_quickstart_game_server_demo }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    TemplateConfigs:
      - Name: 单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions:
          - cn-hangzhou
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: demo
    Image: 'resources/icons/service_logo.png'
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: aliyun-computenest_quickstart_game_server_demo
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/aliyun-computenest_quickstart_game_server_demo.tar.gz'